 # Eric Paulz
 # epaulz@clemson.edu
 # CPSC 1021-004
 # Lab 11
 # Nick Glyder

lab11:	functions.cpp driver.cpp
	g++ -Wall functions.cpp driver.cpp -o lab11

run:	lab11
	./lab11 input1.txt
	./lab11 input2.txt

clean:
	rm lab11
