# Eric Paulz
# CPSC 1010 - Fall 2016
# Lab 10
# October 24, 2016
# -Makefile


arrays: defs.h initArray.c printArray.c findValues.c main.c
	gcc -Wall -o arrays defs.h initArray.c printArray.c findValues.c main.c

run: arrays
	./arrays

clean:
	rm arrays
