 #
 # Eric Paulz
 # CPSC 1021-004
 # Lab #12
 # TA: Nick Glyder
 #

all: driver.cpp functions.cpp
	g++ -Wall driver.cpp functions.cpp -g

run:
	./a.out input1.txt
	./a.out input2.txt

clean:
	rm ./a.out
